GENERAL:
  task: "Task08_HepaticVessel"
  root_dir: "/home/leo/MSD"
  download: False
  split: 0.8
  seed: 0
  num_workers: 8
  cache_rate: 0.0
TRANSFORM:
  patch_size: [ 192, 192, 64 ]
  spacing: [ 0.8,0.8,1.5 ]
  clip_values: [ -3, 243 ]
  normalize_values: [ 104.37, 52.62 ]
  num_samples: 3
  neg_sample_num: 1
  pos_sample_num: 1
TRAIN:
  max_epochs: 600
  batch_size: 2
  deep_supr_num: 3
  gradient_accumulation_steps: 2
  scheduler:
    type: torch.optim.lr_scheduler.CyclicLR
    params:
      base_lr: 5e-6
      max_lr: 5e-4
      step_size_up: 2000
      cycle_momentum: False
  optimizer:
    type: torch.optim.AdamW
    params:
      lr: 5e-6
      weight_decay: 3e-5

