GENERAL:
  task: "Task03_Liver"
  root_dir: "/workspace"
  download: False
  split: 0.8
  seed: 0
  num_workers: 8
  cache_rate: 1.0
TRANSFORM:
  patch_size: [ 128, 128, 128 ]
  spacing: [ 0.75,0.75,1.0 ]
  clip_values: [ -20, 210 ]
  normalize_values: [ 99.40, 39.36 ]
  num_samples: 2
  neg_sample_num: 1
  pos_sample_num: 1
TRAIN:
  max_epochs: 1000
  batch_size: 2
  deep_supr_num: 3
  gradient_accumulation_steps: 1
  scheduler:
    -
      type: monai.optimizers.WarmupCosineSchedule
      end: 1500
      params:
        warmup_steps: 250
        t_total: 1500
        warmup_multiplier: 0.01
  optimizer:
    type: monai.optimizers.Novograd
    params:
      lr: 1.0e-3
      weight_decay: 1.0e-3
      betas: [0.9, 0.98]
      eps: 1.0e-6
      amsgrad: True
  model:
    generator: unetr.get_SwinUNETR
    loss_fn: unetr.loss_fn

